feat(AAE-3195): Add acceptance test for REST API to list Service Tasks
Activiti/activiti-cloud-application pull request #160
Opened 2020-09-24 14:45 UTC by igdianov

2020-09-28 15:46 UTC, erdemedeiros requested changes
One small detail.

2020-09-28 15:46 UTC, erdemedeiros commented on activiti-cloud-acceptance-scenarios/runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/story/ProcessInstanceServiceTasks.java
> +                            .containsExactly("serviceTask");
It's probably better to use `containsOnly` instead of `containsExactly`. Otherwise, this assertion will fail if the list has more than one element.

2020-09-28 16:19 UTC, igdianov commented on activiti-cloud-acceptance-scenarios/runtime-acceptance-tests/src/main/java/org/activiti/cloud/qa/story/ProcessInstanceServiceTasks.java
> +                            .containsExactly("serviceTask");
Fixed.

2020-09-29 08:29 UTC, erdemedeiros approved these changes

2020-09-29 08:32 UTC, merged