[AAE-11278] Spring cloud stream functional bindings preview
Activiti/activiti-cloud-application pull request #828
Opened 2022-12-05 08:52 UTC by jsokolowskii

2023-01-06 14:52 UTC, erdemedeiros approved these changes
LGTM!

2023-01-25 21:03 UTC, igdianov requested changes

2023-01-25 21:03 UTC, igdianov commented on example-cloud-connector/starter/src/main/java/org/activiti/cloud/examples/connectors/ConnectorConfiguration.java
> +    }
Let's refactor this code using functional channel bindings.

2023-01-25 21:03 UTC, igdianov commented on example-cloud-connector/starter/src/main/java/org/activiti/cloud/examples/connectors/MultiInstanceConnector.java
> +    public Void apply(IntegrationRequest event) {
The `apply` method can be implemented directly.

2023-01-25 21:03 UTC, igdianov commented on example-cloud-connector/starter/src/main/java/org/activiti/cloud/examples/connectors/RestConnector.java
> +    public Void apply(IntegrationRequest event) {
The `apply` method can be implemented directly.

2023-01-25 21:03 UTC, igdianov commented on example-cloud-connector/starter/src/main/java/org/activiti/cloud/examples/connectors/TestBpmnErrorConnector.java
> +    public Void apply(IntegrationRequest event) {
The `apply` method can be implemented directly.

2023-01-25 21:03 UTC, igdianov commented on example-cloud-connector/starter/src/main/java/org/activiti/cloud/examples/connectors/TestErrorConnector.java
> +    public Void apply(IntegrationRequest event) {
The `apply` method can be implemented directly.

2023-01-25 21:03 UTC, igdianov commented on example-cloud-connector/starter/src/main/java/org/activiti/cloud/examples/connectors/ExampleConnector.java
> +    public void performTask(IntegrationRequest event) {
The apply method can be implemented directly or via separate Connector function bean that uses ExampleConnector consumer as a delegate.

2023-01-25 21:03 UTC, igdianov commented on example-cloud-connector/starter/src/main/java/org/activiti/cloud/examples/connectors/ExampleConnector.java
> +@ConnectorBinding(input = ExampleConnectorChannels.EXAMPLE_CONNECTOR_CONSUMER, condition = "", outputHeader = "")
Why do you need to reset `outputHeader` attribute?

2023-01-31 08:00 UTC, jsokolowskii commented
The changes were merged in PR #875

2023-01-31 08:00 UTC, closed without merging